---
- name: create standard home directory stuff
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/src'

- name: Install favorite packages from homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - vim
    - bgpq3
    - tmux
    - mtr
    - hping3
    - tshark
    - go
    - cowsay
    - wget
    - nmap
    - mutt
    - htop
    - irssi
    - imagemagick
    - htop-osx
    - jq
    - ettercap
    - aspell


- name: Install favorite packages from homebrew_cask
  homebrew_cask: name={{ item }} state=present
    - google-chrome
    - virtualbox
    - vagrant
    - sublime-text
    - transmit
    - spotify
    - adium
    - vlc
    - skype

- name: install dotfiles via git (requires private key first)
  git: repo=git@ardberg.nyc.ipstuff.ca:cmurray/dotfiles.git
       dest={{ home }}/src/dotfiles
       update=no

- name: Install python goodies
  pip: name={{ item }} state=present
    - paramiko
    - virtualenv
    - virtualenvwrapper
    - six
    - python-nmap
    - pylibpcacp
    - netaddr
    - pbr
    - ncclient
    - lxml
    - Jinja2
    - PyASN
    - PyYAML
    - dnspython
    - matplotlib
    - pyOpenSSL
    - typogrify
    - vboxapi
    - SQLAlchemy
    - Fabric
    - Flask
    - Flask-Babel
    - Flask-Login
    - Flask-OpenID
    - Flask-SQLAlchemy
    - Flask-WTF
    - Flask-WhooshAlchemy
    - Markdown
    - junos-eznc
    - pelican
