- name: Install python goodies
  pip: name={{ item }} state=present
  with_items:
    - paramiko
    - virtualenv
    - virtualenvwrapper
    - six
    - python-nmap
#    - pylibpcap
    - netaddr
    - pbr
    - ncclient
    - lxml
    - Jinja2
#    - PyASN
    - PyYAML
    - dnspython
    - matplotlib
    - pyOpenSSL
    - typogrify
    - vboxapi
    - SQLAlchemy
    - Fabric
    - Flask
    - Flask-Babel
    - Flask-Login
    - Flask-OpenID
    - Flask-SQLAlchemy
    - Flask-WTF
    - Flask-WhooshAlchemy
    - Markdown
    - junos-eznc
    - pylint
    - pelican

